-- ============================================================
-- DAYANG SPA v2 - SEED DATA AWAL
-- Mengisi: Treatment (global), Terapis (roster per outlet), Stok minyak (0)
-- Cara: tempel di SQL Editor -> Run. AMAN dijalankan ulang (idempotent).
-- ============================================================

-- ---------- TREATMENTS (global) ----------
insert into treatments (name, price, category, duration_minutes, commission_percent, uses_oil) values
  ('Lombok Massage (60 Min)', 200000, 'Massage', 60, 10, true),
  ('Lombok Massage (90 Min)', 300000, 'Massage', 90, 10, true),
  ('Stress Relieving Massage (60 Min)', 200000, 'Massage', 60, 10, true),
  ('Stress Relieving Massage (90 Min)', 300000, 'Massage', 90, 10, true),
  ('Aloevera Massage (60 Min)', 200000, 'Massage', 60, 10, true),
  ('Aloevera Massage (90 Min)', 300000, 'Massage', 90, 10, true),
  ('Balinese Massage (60 Min)', 200000, 'Massage', 60, 10, true),
  ('Balinese Massage (90 Min)', 300000, 'Massage', 90, 10, true),
  ('Thai Massage (60 Min)', 200000, 'Massage', 60, 10, true),
  ('Thai Massage (90 Min)', 300000, 'Massage', 90, 10, true),
  ('After Surf Massage (60 Min)', 200000, 'Massage', 60, 10, true),
  ('After Surf Massage (90 Min)', 300000, 'Massage', 90, 10, true),
  ('Deep Tissue Massage (60 Min)', 200000, 'Massage', 60, 10, true),
  ('Deep Tissue Massage (90 Min)', 300000, 'Massage', 90, 10, true),
  ('Herbal Compress (90 Min)', 400000, 'Massage', 90, 10, true),
  ('Hot Stone (60 Min)', 300000, 'Massage', 60, 10, true),
  ('Hot Stone (90 Min)', 400000, 'Massage', 90, 10, true),
  ('Back, Neck & Shoulder (30 Min)', 100000, 'Massage', 30, 10, true),
  ('Back, Neck & Shoulder (60 Min)', 200000, 'Massage', 60, 10, true),
  ('Head Massage (30 Min)', 100000, 'Massage', 30, 10, false),
  ('Foot Massage (30 Min)', 100000, 'Massage', 30, 10, false),
  ('Foot Massage (60 Min)', 200000, 'Massage', 60, 10, false),
  ('Pedicure Only', 100000, 'Nail', 45, 10, false),
  ('Pedicure + Normal Color', 150000, 'Nail', 45, 10, false),
  ('Pedicure + Gel Color', 250000, 'Nail', 60, 10, false),
  ('Manicure Only', 80000, 'Nail', 30, 10, false),
  ('Manicure + Normal Color', 150000, 'Nail', 45, 10, false),
  ('Manicure + Gel Color', 150000, 'Nail', 45, 10, false),
  ('Just Normal Color', 80000, 'Nail', 20, 10, false),
  ('Just Gel Color', 150000, 'Nail', 30, 10, false),
  ('Nail Art Design (Per Nail)', 20000, 'Nail', 15, 10, false),
  ('Fake Nail (Per Nail)', 30000, 'Nail', 20, 10, false),
  ('Fake Nail (Full)', 280000, 'Nail', 90, 10, false),
  ('BIAB Overlay (Per Nail)', 40000, 'Nail', 20, 10, false),
  ('BIAB Overlay (Full)', 480000, 'Nail', 120, 10, false),
  ('Dinfill BIAB (Per Nail)', 30000, 'Nail', 20, 10, false),
  ('Dinfill BIAB (Full)', 280000, 'Nail', 90, 10, false),
  ('Acrylic (Per Nail)', 40000, 'Nail', 20, 10, false),
  ('Acrylic (Full)', 480000, 'Nail', 120, 10, false),
  ('BIAB Extension (Per Nail)', 50000, 'Nail', 25, 10, false),
  ('BIAB Extension (Full)', 450000, 'Nail', 120, 10, false),
  ('Remove Gel Extension (Per Nail)', 150000, 'Nail', 20, 10, false),
  ('Remove Gel Extension (Full)', 150000, 'Nail', 60, 10, false),
  ('Remove Hard Gel', 100000, 'Nail', 30, 10, false),
  ('Remove Gel', 50000, 'Nail', 20, 10, false),
  ('Foot Scrub (30 Min)', 100000, 'Body Care', 30, 10, false),
  ('Back Scrub (30 Min)', 100000, 'Body Care', 30, 10, false),
  ('Facial Treatment (45 Min)', 150000, 'Body Care', 45, 10, false),
  ('Body Mask/Wrap (45 Min)', 150000, 'Body Care', 45, 10, false),
  ('Body Scrub (45 Min)', 150000, 'Body Care', 45, 10, false),
  ('Ear Candle', 100000, 'Body Care', 30, 10, false),
  ('Bikini Line', 250000, 'Waxing', 30, 10, false),
  ('Brazilian Wax', 300000, 'Waxing', 45, 10, false),
  ('Full Leg', 300000, 'Waxing', 45, 10, false),
  ('Half Leg', 200000, 'Waxing', 30, 10, false),
  ('Arm', 200000, 'Waxing', 30, 10, false),
  ('Half Arm', 120000, 'Waxing', 20, 10, false),
  ('Under Arm', 100000, 'Waxing', 15, 10, false),
  ('Full Stomach/Chest/Back', 300000, 'Waxing', 45, 10, false)
on conflict do nothing;

-- ---------- THERAPISTS (roster per outlet asal) ----------
insert into therapists (name, role, home_outlet_id, status) values
  ('Gading', 'terapis', 'DR', 'free'),
  ('Arya', 'terapis', 'DR', 'free'),
  ('Riska', 'terapis', 'DR', 'free'),
  ('Aisyah', 'terapis', 'DR', 'free'),
  ('Nur', 'terapis', 'DR', 'free'),
  ('Runi', 'terapis', 'DR', 'free'),
  ('Suhir', 'terapis', 'DR', 'free'),
  ('Rian', 'terapis', 'DR', 'free'),
  ('Sahara', 'terapis', 'DR', 'free'),
  ('Indah', 'terapis', 'DR', 'free'),
  ('Nia', 'terapis', 'DR', 'free'),
  ('Samy', 'terapis', 'DR', 'free'),
  ('Tumin', 'terapis', 'RR', 'free'),
  ('Zul', 'terapis', 'RR', 'free'),
  ('Ripan', 'terapis', 'RR', 'free'),
  ('Ulan', 'terapis', 'RR', 'free'),
  ('Anita', 'terapis', 'RR', 'free'),
  ('Aulia', 'terapis', 'RR', 'free'),
  ('Ijal', 'terapis', 'RR', 'free'),
  ('Esi', 'terapis', 'RR', 'free'),
  ('Risma', 'terapis', 'RR', 'free'),
  ('Ayuha', 'terapis', 'RR', 'free'),
  ('Doni', 'terapis', 'RR', 'free'),
  ('Putri', 'terapis', 'RR', 'free'),
  ('Ega', 'terapis', 'DP', 'free'),
  ('Titik', 'terapis', 'DP', 'free'),
  ('Novita', 'terapis', 'DP', 'free'),
  ('Bayu', 'terapis', 'DP', 'free'),
  ('Destia', 'terapis', 'DP', 'free'),
  ('Azi', 'terapis', 'DP', 'free'),
  ('Uswa', 'terapis', 'DP', 'free'),
  ('Ira', 'terapis', 'DP', 'free'),
  ('Fitri', 'terapis', 'DP', 'free'),
  ('Try', 'terapis', 'DP', 'free'),
  ('Panji', 'terapis', 'D1', 'free'),
  ('Ron', 'terapis', 'D1', 'free'),
  ('Maya', 'terapis', 'D1', 'free'),
  ('Rizal', 'terapis', 'D1', 'free'),
  ('Ily', 'terapis', 'D1', 'free'),
  ('Laura', 'terapis', 'D1', 'free'),
  ('Fenti', 'terapis', 'D2', 'free'),
  ('Feri', 'terapis', 'D2', 'free'),
  ('Lia', 'terapis', 'D2', 'free'),
  ('Riri', 'terapis', 'D2', 'free'),
  ('Sumi', 'terapis', 'D2', 'free'),
  ('Ayy', 'terapis', 'Y', 'free'),
  ('Reno', 'terapis', 'Y', 'free'),
  ('Misna', 'terapis', 'Y', 'free'),
  ('Pian', 'terapis', 'Y', 'free')
on conflict do nothing;

-- ---------- STOK MINYAK (semua outlet, default 0) ----------
insert into oil_inventory (outlet_id, oil_type, size, stock, unit)
select o.id, oi.oil_type, oi.size, 0, 'botol'
from (values ('DR'),('RR'),('DP'),('D1'),('D2'),('Y')) o(id)
cross join (
  values ('Relaxing','Kecil'),('Relaxing','Besar'),
         ('Refreshing','Kecil'),('Refreshing','Besar'),
         ('Herbal','Kecil'),('Herbal','Besar'),
         ('Hot Oil','Kecil'),('Hot Oil','Besar'),
         ('Cem-Ceman','Kecil'),('Cem-Ceman','Besar'),
         ('Aromatic Oil','Kecil'),('Aromatic Oil','Besar')
) oi(oil_type, size)
on conflict (outlet_id, oil_type, size) do nothing;
